import { Quicksand } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const quicksand = Quicksand({
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={quicksand.className}>
        {children}
        <Toaster
          richColors
          position="bottom-right"
          toastOptions={{
            style: {
              fontFamily: "Quicksand, sans-serif",
            },
          }}
        />
      </body>
    </html>
  );
}
